# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-06 23:32
from __future__ import unicode_literals

import Blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_post_author_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_email',
            field=models.CharField(blank=True, max_length=240, null=True, validators=[Blog.models.validate_author_email, Blog.models.validate_algo]),
        ),
    ]
