# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-06 23:40
from __future__ import unicode_literals

import Blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20180206_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_email',
            field=models.EmailField(blank=True, max_length=240, null=True, validators=[Blog.validators.validate_author_email, Blog.validators.validate_algo]),
        ),
    ]
