# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_auto_20180213_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.CharField(choices=[('draft', 'Draft'), ('public', 'Public'), ('publish', 'Publish'), ('private', 'Private')], default='draft', max_length=120),
        ),
    ]
